
jobs:
  - script: >
      pipelineJob('Backend-Tests') {
        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                options {
                    ansiColor('xterm')
                }
                stages {
                  stage('1/X: Download DevOps and Backend') {
                    steps {
                      sh \'\'\'
                        bash $WORKSPACE/../Backend-Deploy-v1/1bd-download.sh
                      \'\'\'
                    }
                  }

                  stage('2/X: unitary tests') {
                    steps {
                      sh \'\'\'
                        bash $WORKSPACE/2bt-run-unitary-tests.sh
                      \'\'\'
                    }
                  }
                } // end stages
                post {
                    always {
                        sh \'\'\'
                            mkdir -p $JENKINS_HOME/userContent
                            source "/var/jenkins_home/workspace/0_scripts/temp_env_file_functions.sh"
                            remove_copied_env_file "$WORKSPACE/$BUILD_NUMBER/.env"
                        \'\'\'
                    }
                    success {
                        sh \'\'\'
                            SUCCESS_FILE="/var/jenkins_home/workspace/0_static/badge_success.svg"
                            NEXUS_URL="http://nexus:8081/repository/public-files/images/tests-result.svg"
                            curl -i -u ^${MY_USER}:^${MY_PASS} -X PUT --upload-file $SUCCESS_FILE $NEXUS_URL
                        \'\'\'
                    }
                    failure {
                        sh \'\'\'
                            FAILURE_FILE="/var/jenkins_home/workspace/0_static/badge_failing.svg"
                            NEXUS_URL="http://nexus:8081/repository/public-files/images/tests-result.svg"
                            curl -i -u ^${MY_USER}:^${MY_PASS} -X PUT --upload-file $FAILURE_FILE $NEXUS_URL
                        \'\'\'
                    }
                    
              }
                }
            '''.stripIndent())
          }
        }
      }

