jobs:
  - script: >
      pipelineJob('Frontend-Rollback') {

        definition {
          cps {
            script('''
              pipeline {
                agent { label 'built-in' }
                options {
                    ansiColor('xterm')
                }

                
                stages {
                  
                  stage('1/4: Download DevOps Project') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/../Frontend-Deploy-v1/1fd-download.sh
                      \'\'\'
                    }
                  }

                  stage('2/4: Backup And Delete Last Commit') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/2fr-backup-and-delete-last-commit.sh
                      \'\'\'
                    }
                  }


                  stage('3/4: Download Penultimate Commit') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/../Frontend-Deploy-v1/1fd-download.sh
                      \'\'\'
                    }
                  }


                  stage('4/4: Build image') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/../Frontend-Deploy-v1/2fd-build-image.sh
                      \'\'\'
                    }
                  }

                  stage('4/5: Deploy') {
                    steps {
                      sh \'\'\'
                        source $WORKSPACE/../Frontend-Deploy-v1/3fd-deploy.sh
                      \'\'\'
                    }
                  }

                }
              }
            '''.stripIndent())
          }
        }
      }
